//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLabServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Identification_Table
    {
        public int id { get; set; }
        public int id_MO { get; set; }
        public int id_test { get; set; }
        public Nullable<int> res { get; set; }
    
        public virtual Microorganism Microorganism { get; set; }
        public virtual Test Test { get; set; }
    }
}
