//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLabServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Microorganism
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Microorganism()
        {
            this.Identification_Table = new HashSet<Identification_Table>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string abbreviated_name { get; set; }
        public Nullable<int> id_group_MO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Identification_Table> Identification_Table { get; set; }
        public virtual Microorganisms_groups Microorganisms_groups { get; set; }
    }
}
