//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLabServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_AB_MO_group_profile
    {
        public int id { get; set; }
        public int id_AB { get; set; }
        public Nullable<int> id_group_MO { get; set; }
        public Nullable<int> Res { get; set; }
        public Nullable<int> Sen { get; set; }
    
        public virtual Antibiotic Antibiotic { get; set; }
        public virtual Microorganisms_groups Microorganisms_groups { get; set; }
    }
}
