//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLabServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_Study_CategoryPatient
    {
        public int id { get; set; }
        public int id_purpose_of_study { get; set; }
        public int id_category_of_patient { get; set; }
    
        public virtual Category_of_patient Category_of_patient { get; set; }
        public virtual Purpose_of_study Purpose_of_study { get; set; }
    }
}
