//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BacLabServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purpose_of_study
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purpose_of_study()
        {
            this.p_Study_CategoryPatient = new HashSet<p_Study_CategoryPatient>();
        }
    
        public int id { get; set; }
        public string study { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_Study_CategoryPatient> p_Study_CategoryPatient { get; set; }
    }
}
